server:
    port: 8082
spring:
  application:
    name: gt-api

  datasource:
    url: jdbc:mysql://106.75.115.170:3306/gn-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: gwk_632697105qq
    druid:
      initial-size: 10
      min-idle: 40
      max-active: 80
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid


